# Generated by Django 4.2.1 on 2024-05-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_listing_category_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Art", "Art"),
                    ("Clothing & Accessories", "Clothing & Accessories"),
                    ("Electronics", "Electronics"),
                    ("Home Goods", "Home Goods"),
                    ("Sports & Outdoor", "Sports & Outdoor"),
                    ("Books & Media", "Books & Media"),
                    ("Others", "Others"),
                ],
                default="Others",
                max_length=50,
            ),
        ),
    ]
